plugins {
    id "com.android.application"
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file("keystore.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
} else {
    Runtime.getRuntime().exec(new String[]{
            "keytool", "-genkeypair",
            "-v", "-keystore", "${System.getProperty("user.home")}/debug.keystore",
            "-storepass", "android",
            "-keypass", "android",
            "-alias", "androiddebugkey",
            "-keyalg", "RSA",
            "-keysize", "2048",
            "-validity", "10000",
            "-dname", "CN=Android Debug,O=Android,C=US"
    }).waitFor()
}

android {
    namespace = "com.trans.pvztv"
    ndkVersion = "27.2.12479018"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.trans.pvztv"
        minSdk = 21
        targetSdk = 33
        versionCode = 2
        versionName = "0.0.0"
        versionNameSuffix = "-${'git log --date=format:%y%m%d --pretty=format:%cd -n 1'.execute().text.trim()}"

        ndk {
            abiFilters "armeabi-v7a"
        }

        buildConfigField("String", "GIT_COMMIT_SHA", "\"${'git rev-parse --short HEAD'.execute().text.trim()}\"")
    }

    signingConfigs {
        // 本文件已被 git 跟踪, 不要在此处修改签名配置, 需要自定义签名配置请参考 README.md
        release {
            keyAlias = keystoreProperties.getProperty("keyAlias", "androiddebugkey")
            keyPassword = keystoreProperties.getProperty("keyPassword", "android")
            storeFile = file(keystoreProperties.getProperty("storeFile", "${System.getProperty("user.home")}/debug.keystore"))
            storePassword = keystoreProperties.getProperty("storePassword", "android")
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
        }

        relWithDebInfo {
            applicationIdSuffix = ".debug"
            signingConfig = signingConfigs.debug
            debuggable = true
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
                }
            }
        }

        release {
            signingConfig = signingConfigs.release
            externalNativeBuild {
                cmake {
                    arguments "-DCMAKE_BUILD_TYPE=Release"
                }
            }
            /* Uncommenting will cause a crash. */
            // minifyEnabled = true
            // shrinkResources = true
        }
    }

    flavorDimensions += "version"

    productFlavors {
        // w 代替 v 以降低默认优先级
        register("w111") {
            dimension = "version"
            applicationId = "com.trans.pvz"
            versionName = "1.1.1"
            externalNativeBuild {
                cmake {
                    arguments "-DPVZ_VERSION=111"
                }
            }
        }

        register("v115") {
            dimension = "version"
            versionName = "1.1.5"
            externalNativeBuild {
                cmake {
                    arguments "-DPVZ_VERSION=115"
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    externalNativeBuild {
        cmake {
            path = "src/main/cpp/CMakeLists.txt"
        }
    }

    buildFeatures {
        buildConfig = true
    }

    lintOptions {
        checkReleaseBuilds = false
        abortOnError = false
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            outputFileName = "PvZ-TV-v${variant.versionName}-${variant.buildType.name}.apk"
        }
    }
}

dependencies {
    implementation fileTree("dir": "libs", "include": ["*.jar"])
    implementation 'androidx.annotation:annotation:1.9.1'
}
